=begin
  You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"

find original: https://leetcode.com/problems/find-the-difference/description/

=end

def find_the_dif(s, t)
  s_t = s.chars.tally
  t_t = t.chars.tally
  t_t.each do |k, v|
    return k if t_t[k] != s_t[k]
  end
end
